### PR TITLE
Interface: Added a function to get/set the ARM9 next instruction

### PR DESCRIPTION
**Pull request by theCapypara**

### CODE REVIEW

**Comment by zeromus** [comment]
did you test this with the jit enabled?

**Comment by theCapypara** [comment]
I didn't; I will add a comment pointing out it's untested with JIT on for now.

**Comment by theCapypara** [comment]
I changed it to return 0 for the getter and be a no-op for the setter. I can also change it to crash instead, but I feel like this is a bit less radical, given that this is supposed to be linked by another process. Whoever is calling is is responsible to make sure JIT is disabled (which as of right now there's no way to enable it from the interface anyway).

**Comment by zeromus** [comment]
ok I would still rather it abort but whatever

**Pull request merged**
